version: 2

builds:
  - main: ./cmd/mapkubeapis
    binary: mapkubeapis
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - id: archive
    format: tar.gz
    files:
      - README.md
      - LICENSE
      - plugin.yaml
      - scripts/install_plugin.sh
      - config/Map.yaml
checksum:
  name_template: 'checksums.txt'
